{% set name = "pyjnius" %}
{% set version = "1.1.3" %}
{% set build_number = 1001 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: 0bc70b48eb764b20b017e44ef2df6eae94e4a2f90ae63160d2a166c406e1ccf9
  # Currently testing on pyjnius master
  url: https://github.com/kivy/pyjnius/archive/8aa91781f6d7726f9eb04fb8b1fb913be0ba1f4c.zip
  sha256: 301d3e1bc6105ccc3fb1a887cef0aa84557270365ff62d818f6bef1197903733

  patches:
    - fix_setup.py.patch

build:
  number: {{ build_number }}
  skip: true  # [py2k]

requirements:
 build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
 host:
   - openjdk
   - python
   - cython
   - pip
   - six >=1.7.0
   - nose
   - ant
 run:
   - openjdk
   - python
   - six >=1.7.0
   - setuptools

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: "A Python module to access Java classes as Python classes using JNI (shared memory)."

extra:
  recipe-maintainers:
     - hanslovsky
     - hadim
