{% set name = "pyjnius" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kivy/pyjnius/archive/{{ version }}.zip
  sha256: bc446196b4b8b5d6dbf825657c597e4ac48f1fa40ac92c3b2b6d55d75f00b16a

build:
  number: 1001
  skip: true  # [py2k]

requirements:
 build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
 host:
   - openjdk
   - python
   - cython
   - pip
   - six >=1.7.0
   - nose
   - ant
 run:
   - openjdk
   - python
   - six >=1.7.0
   - setuptools

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: "A Python module to access Java classes as Python classes using JNI (shared memory)"

extra:
  recipe-maintainers:
     - hanslovsky
     - hadim
