{% set name = "pyjnius" %}
{% set version = "1.1.3" %}
{% set build_number = 1001 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: 0bc70b48eb764b20b017e44ef2df6eae94e4a2f90ae63160d2a166c406e1ccf9
  # Currently testing on https://github.com/kivy/pyjnius/pull/364
  url: https://github.com/kivy/pyjnius/archive/5cda4258847a8d47c4b04ee1de3627132355b510.zip
  sha256: 525ad5e07011c667d4c56f0341403eef082b49a90290e13fdc2ef75102082758


build:
  number: {{ build_number }}
  skip: true  # [py2k]

requirements:
 build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
   - openjdk
 host:
   - openjdk
   - python
   - cython
   - pip
   - six >=1.7.0
   - nose
   - ant
 run:
   - openjdk
   - python
   - six >=1.7.0
   - setuptools

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: A Python module to access Java classes as Python classes using JNI (shared memory).

extra:
  recipe-maintainers:
     - hanslovsky
     - hadim
