{% set name = "pyjnius" %}
{% set version = "1.1.3" %}
{% set build_number = 1001 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kivy/pyjnius/archive/{{ version }}.tar.gz
  sha256: 67b4031752cb32213cefd672b2792f3e75791e68bfd1ca7a5d328ff00acc1622

build:
  number: {{ build_number }}
  skip: true  # [py2k]

requirements:
 build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
 host:
   - openjdk
   - python
   - cython
   - pip
   - six >=1.7.0
   - nose
   - ant
 run:
   - openjdk
   - python
   - six >=1.7.0
   - setuptools

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: A Python module to access Java classes as Python classes using JNI (shared memory).

extra:
  recipe-maintainers:
     - hanslovsky
     - hadim
