{% set name = "pyjnius" %}
{% set version = "1.1.3" %}
{% set build_number = 1001 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: 0bc70b48eb764b20b017e44ef2df6eae94e4a2f90ae63160d2a166c406e1ccf9
  #url: https://github.com/kivy/pyjnius/archive/940b039a2a7859835890f08bb6e7c47a689e83b0.zip
  #sha256: de347b0413b75546d61b9604db17b10c68d1f614c40a33f992c477c8f3cbecef
  url: https://github.com/hadim/pyjnius/archive/fix-osx.zip
  sha256: b34a387bde8606956de4436527efd42fdd093df332e8c45d2179df5f10819f94


build:
  number: {{ build_number }}
  skip: true  # [py2k]

requirements:
 build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
 host:
   - openjdk
   - python
   - cython
   - pip
   - six >=1.7.0
   - nose
   - ant
 run:
   - openjdk
   - python
   - six >=1.7.0
   - setuptools

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: A Python module to access Java classes as Python classes using JNI (shared memory).

extra:
  recipe-maintainers:
     - hanslovsky
     - hadim
