# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_openjdk10python3.6
    - CONFIG=osx_openjdk10python3.7
    - CONFIG=osx_openjdk11python3.6
    - CONFIG=osx_openjdk11python3.7
    - CONFIG=osx_openjdk8python3.6
    - CONFIG=osx_openjdk8python3.7
    - CONFIG=osx_openjdk9python3.6
    - CONFIG=osx_openjdk9python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BiCJmPN9jdgBrppK8cWlAuiRkZ6Cqdh5RSDNUclAYezII/s8DN8H3bqUGSzLPS3C6H8lXYB1lOgA7YjKGOqQ1MDGOOUI9TWnDvaxhNZ9ATe4/vj2/rvSJCs2kJXKo5N/JynWXtHTaxHOtMVJVIepgGkemjTGn4AqdhrM2mUEdpZiC0h3Xy8IpK3O85IL8P8L612DRV8PfyFTzSbnnALJjTzNvbH0rCxWxn6Lq3sTRB21pkYp46ZbmGEaL0w9/AvlcAev6OnZ3+hzj2JRw+jh4mvGUON8mgm4kIapGHE+C61nQL/Z2RErVdwRFucLuIOX+XYVkNZCssrQyDQolx99MZuFf65xL3JxymtGMqJXsmhiBaoFHNy5YpVzxcMHbWV0etdYRyVCit2Z0Z26aUpfA0sXRRgkI5QZCOMBJFVzBJxqu00/FFvM9KxbLJ+itHfuYtU8fs2nlFi3Epd+kamY3Jkt/JGCkVaCl9WRb5Fj7DF1x5eHzNEBzbCLzUtayv8v6EyiKXc8f6ugHPFh3DRf/Stdz9W65XNaK59gBdHmPfvN1j0zlwBzrPRh1/dtXBhJ+fw4/X4iyVeSJy5jo7Q74DG+jdQLaWE/htZZLfkAWfXFxS4KBlVL9oP46q126umLMatCIz1lbqf+LyGvdP0lmGF0uT6ClE1FmypGqMmiK9c="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml