travis:
  secure:
    BINSTAR_TOKEN: K7tEI0Lx+T1DHRrZgsjS5l0NiHKVNktwedlWhiV1biqvj2tKubm3/9HB4O6kaqgsTHX1QI7QUntO9lUTP02gDuiohrUBMiPwONIMC50K0jKr0ne9WMBA+HBER4wnqlB/Habc5INV8CGm9IT2RDNYtkWPBX13/qEVvuOB5SrT7C3xpTnC//7AY0/Duc9Stj0XmZcXAXO5deGdual83xA8WF5G5lZdXSDhRO81GSyluKGhP5IsD9HJnr12Uq3DVCo7dIjTxHtW3zgi5uvlF0/NwMC4BT4ppUMVyL7IWpiYBeGXb9XIGtlmcxkkcb1oeu4OxbHFDl6NHsnzQCl392LkND8+lwHFnHknwnBEab/q9BuI22GvjY1Ku0xTu4mHkjEcrhhzNbURcPHCWU4Qr5a/BkPvW0ZnOYi4VVAYsf+S33Oi73rpLXDJIvGAXhJYfHk/tiQo4aJkZd+inTsxozBji+9kuSK9Q6m0mvfjK6fgWYTjrLbqAbJTfxr698cPFwyq07aIoAvURdRXB0AgNItnsXckwWrEK7qBa8VdgSnL0ciOW+pGsekFXjc1EezY9RZIe5ycCYrj6AvWI3kckl+l+ifRfkrBniMnlwRKFDViX4XnqVWJ9iqlG/B2Zpsr8zgKWRJT132Jy7T3salM1PohdD0LbRPt3G96Qr1K3PozSI4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
