travis:
  secure:
    BINSTAR_TOKEN: gc6iWEE5FqIHnuWVycuvuswWr8w1NOqQqzMHbbn262r9nVGoRB2ZybQtqM9ZIlmoaZx4j5lOXbepmNo6B4XJUfl3/amiA1YA9spH5bGAhIZGsyjzNpr0gS4dn/UDT71cCtZhlrEjyMmvayCO82eQ3gEI1S+ac/cFS0wByDANb/JJzxpPgMdo/pyHmjRi3GT1hCcdMgAypG0/IqhtiPd0BT/poGWzVGbkUNv/zRqty6zJ2gWs55sDTl4LGjdkAoLT1MtTO70piN8/If+nmzoP2rqGDVUJsHwFEFZNDiKl50+Yv6ruKd/fkALkWnXJyYY3jRSotT6H/vkBxoCTGhN5iO9aTpjByshroJdohCKKWxiwSPsCosdFjeDL3gdi+h6QA/u8V5WrogFnm2hiJkcZAnycKd3SjrBbzwFuRTyn4y9PDCVy2IfGdX88FIMgx9ff2G0zaZuvgQ6utrEbSZoNUAVEsytsn2tv3OpQqmYDoAujXJahGhuPE8NBDnAyFa3P+6SqwJ6zTzmwLUuSy+SpeRcCY9YLEUZ0gEEPv/BXdss0CB9i7Y18Z/G4+KwOHbea8I1jHFOEQYWoJJWUadcqKxSoSo1QgA49OihR6LE8TOkXl3hkdzxNqInJ1MBr4Mpa5zQ10CfQR4GQABt65xt1CkYnKx+z8WzfsPG9QS6WXas=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
